sudo: false

language: java
jdk:
  - oraclejdk8
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notification:
  email:
    on_success: never
    on_failure: always
